### ISSUE TITLE
Handling non-local resources

### ISSUE THREAD

**Issue by justinribeiro** [jeffposnick/sw-precache#18]
Not sure where the roadmap is headed, but has there been any consideration for a use case where non-local resources might want/need to be cached? An example might be that in defining  ```staticFileGlobs``` we might point to a resource on a CDN (for the sake of argument, let's say an image).

At the moment, sw-precache will ignore such a resource (```getFileAndSizeAndHashForFile()``` will return null in the process of verifying the file on the local filesystem, which is obviously not there) and the SW isn't setup to handle mapping outside the existing domain (```populateCurrentCacheNames()``` sets a baseUrl via self.location for mappings and handling requests would need no-cors mode).

I suppose my question boils down to:

1. Is this a feature that is needed/wanted/planned?
2. If yes, is there a preferred approach to that implementation? 

I can think of a couple of different ways to go about this and I'm willing to put in some time to dev that feature out if it would be useful.

**Comment by jeffposnick** [comment]
I don't think that's going to be within scope for `sw-precache`, (so I'm closing this issue) but it's an important use case in general.

What I've done when working on projects that rely on both local and cross-domain resources is to use both `sw-precache` and another library, [`shed`](https://github.com/wibblymat/shed). They play nicely together if you load the core `shed` dependency and configuration scripts that control `shed` behavior via [`importScripts`](https://github.com/jeffposnick/sw-precache#importscripts-arraystring).

I'd recommend checking `shed` out, and passing along any feedback to @wibblymat via the [issue tracker](https://github.com/wibblymat/shed/issues).

**Comment by justinribeiro** [comment]
Appreciate the feedback @jeffposnick Very much like [shed](https://github.com/wibblymat/shed) (I'm using it on a greenfield project at the moment), and will pass along feedback there. Cheers!
