### ISSUE TITLE
Can't run with Grunt

### ISSUE THREAD

**Issue by ozasadnyy** [jeffposnick/sw-precache#19]
Sorry for the stupid question, but how to use this plugin in the project?
I have tried to run `$ grunt` from [demo](https://github.com/jeffposnick/sw-precache/tree/master/demo) folder, but it gives me following error:
```
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
```

**Comment by jeffposnick** [comment]
Please pull in the latest updates and run `npm install` again.

(Or just run `npm install grunt` from the top-level directory with your current copy.)

**Comment by ozasadnyy** [comment]
Unfortunatelly it doesn't work...
```
F:\development\web\sw-precache-master\demo>grunt
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by jeffposnick** [comment]
Try running `grunt swPrecache`

It's probably obviously, but the demo `Gruntfile.js` is bare-bones compared to the `gulpfile.js`. It's not as much of a standalone demo as it is a specific task that you could rip out and use in your own `Grunt` configuration.

**Comment by ozasadnyy** [comment]
It works. Thanks!
But it would be complicated to use in real projects. Hope you will rewrite it as most grunt plugins on the web.
Thanks in advance.
