### ISSUE TITLE
Use path.join()/path.sep instead of string concatenation

### ISSUE THREAD

**Issue by jeffposnick** [jeffposnick/sw-precache#6]
There are a number of places that needs to be changed. (Though [**not** in the `glob` patterns](https://github.com/isaacs/node-glob#windows).)

The [logic](https://github.com/jeffposnick/sw-precache/blob/master/sw-precache.js#L78) that translates between file paths and relative URLs also needs to account for `path.sep`.

**Comment by sindresorhus** [comment]
> (Though not in the glob patterns.)

If you accept user input in them you have to as you don't know whether they'll and a path with a `/`. You can always replace `\` with `/` before passing it to node-glob though.
